# Generated by Django 5.1.3 on 2024-11-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id_books', models.AutoField(primary_key=True, serialize=False)),
                ('nome_livro', models.CharField(db_column='nome_livro', max_length=45)),
                ('nome_autor', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'books',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('email_us', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=45)),
                ('livros_favoritos', models.ManyToManyField(related_name='Favoritados', to='back_login.books')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
