# Generated by Django 5.1.3 on 2024-11-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
