# Generated by Django 5.1.3 on 2024-11-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_login', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='livros_favoritos',
            new_name='user_livros_favoritos',
        ),
    ]
