# Generated by Django 5.1.3 on 2024-11-26 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_login', '0003_rename_livros_favoritos_user_user_livros_favoritos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_livros_favoritos',
            new_name='livros_favoritos',
        ),
    ]
